import { SearchResult } from "../types";

export function generateMockResults(query: string): SearchResult[] {
  const q = query.toLowerCase();

  // If the query looks like it's about the Nicole Saldaña shoes, return tailored results
  if (q.includes("nicole") || q.includes("saldaña") || q.includes("saldana") || q.includes("fabiana") || q.includes("mary jane")) {
    return [
      {
        id: "mock-pm-1",
        title: "Nicole Saldaña Fabiana Eyelet Napa Mary Jane - Dark Brown",
        price: 285,
        originalPrice: 470,
        currency: "USD",
        platform: "poshmark",
        url: "https://poshmark.com/listing/nicole-saldana-fabiana",
        imageUrl: "https://placehold.co/400x500/2d2d2d/white?text=Nicole+Salda%C3%B1a%0AFabiana+MJ",
        condition: "Like New",
        size: "38",
        brand: "Nicole Saldaña",
        seller: "luxefinds22",
      },
      {
        id: "mock-trr-1",
        title: "Nicole Saldaña Fabiana Leather Mary Jane Flats",
        price: 195,
        originalPrice: 470,
        currency: "USD",
        platform: "therealreal",
        url: "https://therealreal.com/products/nicole-saldana-fabiana",
        imageUrl: "https://placehold.co/400x500/004225/white?text=Nicole+Salda%C3%B1a%0AThe+RealReal",
        condition: "Very Good",
        size: "38.5",
        brand: "Nicole Saldaña",
      },
      {
        id: "mock-dep-1",
        title: "Nicole Saldaña Fabiana Mary Jane Dark Brown Napa Leather",
        price: 320,
        originalPrice: 470,
        currency: "USD",
        platform: "depop",
        url: "https://depop.com/products/nicole-saldana-fabiana",
        imageUrl: "https://placehold.co/400x500/ff2300/white?text=Nicole+Salda%C3%B1a%0ADepop",
        condition: "Good",
        size: "39",
        brand: "Nicole Saldaña",
        seller: "vintageshoes_co",
      },
      {
        id: "mock-tu-1",
        title: "Nicole Saldaña Brown Leather Mary Jane Shoes",
        price: 149,
        originalPrice: 470,
        currency: "USD",
        platform: "thredup",
        url: "https://thredup.com/product/nicole-saldana-fabiana",
        imageUrl: "https://placehold.co/400x500/00a98f/white?text=Nicole+Salda%C3%B1a%0AThredUp",
        condition: "Good",
        size: "38",
        brand: "Nicole Saldaña",
      },
      {
        id: "mock-pm-2",
        title: "Nicole Saldaña Fabiana Eyelet Mary Jane Size 37",
        price: 350,
        originalPrice: 470,
        currency: "USD",
        platform: "poshmark",
        url: "https://poshmark.com/listing/nicole-saldana-fabiana-2",
        imageUrl: "https://placehold.co/400x500/7b2a8f/white?text=Nicole+Salda%C3%B1a%0APoshmark",
        condition: "New with Tags",
        size: "37",
        brand: "Nicole Saldaña",
        seller: "shoecloset",
      },
      {
        id: "mock-trr-2",
        title: "Nicole Saldaña Napa Mary Jane Pumps",
        price: 225,
        originalPrice: 470,
        currency: "USD",
        platform: "therealreal",
        url: "https://therealreal.com/products/nicole-saldana-fabiana-2",
        imageUrl: "https://placehold.co/400x500/004225/white?text=Nicole+Salda%C3%B1a%0ATRR+%232",
        condition: "Good",
        size: "39",
        brand: "Nicole Saldaña",
      },
    ];
  }

  // Generic mock results for any other query
  return [
    {
      id: "mock-pm-gen-1",
      title: `${query} - Excellent Condition`,
      price: 45,
      originalPrice: 120,
      currency: "USD",
      platform: "poshmark",
      url: "https://poshmark.com/listing/example-1",
      imageUrl: `https://placehold.co/400x500/7b2a8f/white?text=${encodeURIComponent(query.slice(0, 20))}%0APoshmark`,
      condition: "Excellent",
      brand: query.split(" ")[0],
      seller: "seller123",
    },
    {
      id: "mock-dep-gen-1",
      title: `${query} - Vintage Find`,
      price: 38,
      originalPrice: 95,
      currency: "USD",
      platform: "depop",
      url: "https://depop.com/products/example-1",
      imageUrl: `https://placehold.co/400x500/ff2300/white?text=${encodeURIComponent(query.slice(0, 20))}%0ADepop`,
      condition: "Good",
      brand: query.split(" ")[0],
      seller: "vintagefinds",
    },
    {
      id: "mock-trr-gen-1",
      title: `${query} - Authenticated`,
      price: 89,
      originalPrice: 250,
      currency: "USD",
      platform: "therealreal",
      url: "https://therealreal.com/products/example-1",
      imageUrl: `https://placehold.co/400x500/004225/white?text=${encodeURIComponent(query.slice(0, 20))}%0AThe+RealReal`,
      condition: "Very Good",
      brand: query.split(" ")[0],
    },
    {
      id: "mock-tu-gen-1",
      title: `${query} - Like New`,
      price: 29,
      originalPrice: 80,
      currency: "USD",
      platform: "thredup",
      url: "https://thredup.com/product/example-1",
      imageUrl: `https://placehold.co/400x500/00a98f/white?text=${encodeURIComponent(query.slice(0, 20))}%0AThredUp`,
      condition: "Like New",
      brand: query.split(" ")[0],
    },
  ];
}
